### ISSUE TITLE
Enhance builds with `npm prune --production` in the Dockerfile

### ISSUE THREAD

**Issue by kasir-barati** [Saluki/nestjs-template#19]
In the builder stage, [In the Dockerfile, in line 25](https://github.com/Saluki/nestjs-template/blob/master/Dockerfile#L25) you run `npm ci` command, and after the builder stage, in the final stage you [run `npm ci` again](https://github.com/Saluki/nestjs-template/blob/master/Dockerfile#L40). 

But why? your base images are the same and these steps happen after each other. I think it was a better idea to copy the node_modules from the builder stage. And as a side note; you do not use `npm ci --only=dev` in the builder step and `npm ci --only=prod`

SO WHY?

**Comment by Saluki** [comment]
Hi @nodejsdeveloperskh :wave: 

The major difference between the 2 calls to `npm ci` is located in the `NODE_ENV` environment variable. This variable tells NPM if the command is launched in a production environment or not. In the first Docker stage (the build stage) our `NODE_ENV` variable is set to `build` (it could also be set to develop or testing) and the `npm ci` will therefore install all dependencies - even the development dependencies. This is essentiel because we need to build the TypeScript code and require the presence of development dependencies.

In the second stage (which will be our final Docker image) we have moved the Node.js code in the image and require only the production dependencies. We therefore set the `NODE_ENV` to `production` and `npm ci` will only install the production dependencies. This ensures that we only have the required Node.js components in the final Docker image.

I hope this answers your question :+1:

**Comment by kasir-barati** [comment]
@Saluki Thanks for the reply. Yup, I am inattention to the details. but I think you could do it simpler by `npm prune --production` in the second stage. after that you could copy the `node_modules` like the `dist` directory. unless you use the different base images in the stages.

**Comment by Saluki** [comment]
This is indeed an excellent proposal, I didn't know `npm prune` could target production dependencies only. I will reopen the issue since it may be an interesting Docker build optimization.

**Comment by Saluki** [comment]
Hello @nodejsdeveloperskh,

The new Dockerfile is now on the master branch & everything is working fine - thanks for the contribution.
